services:
  eureka-server:
    build:
      context: ./server-registry
    container_name: server-registry
    ports:
      - "8761:8761"
    networks:
      - backend

  user-db:
    image: postgres:15
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - user-db
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      USER_SERVICE_DB_HOST: ${USER_SERVICE_DB_HOST}
      USER_SERVICE_DB_PORT: ${USER_SERVICE_DB_PORT}
      USER_SERVICE_DB_NAME: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9081:9081"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9080,PLAINTEXT_LOCAL://localhost:9081
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9080,PLAINTEXT_LOCAL://0.0.0.0:9081
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - backend
    command: >
      bash -c "rm -rf /var/lib/kafka/data/* && /etc/confluent/docker/run"

  team-db:
    image: postgres:15
    container_name: team-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${TEAM_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - team-db-data:/var/lib/postgresql/data
    networks:
      - backend

  team-service:
    build:
      context: ./team-service
    container_name: team-service
    depends_on:
      - zookeeper
      - kafka
      - team-db
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TEAM_SERVICE_DB_HOST: ${TEAM_SERVICE_DB_HOST}
      TEAM_SERVICE_DB_PORT: ${TEAM_SERVICE_DB_PORT}
      TEAM_SERVICE_DB_NAME: ${TEAM_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  plan-db:
    image: postgres:15
    container_name: plan-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${PLAN_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - plan-db-data:/var/lib/postgresql/data
    networks:
      - backend

  plan-service:
    build:
      context: ./plan-service
    container_name: plan-service
    depends_on:
      - zookeeper
      - kafka
      - plan-db
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PLAN_SERVICE_DB_HOST: ${PLAN_SERVICE_DB_HOST}
      PLAN_SERVICE_DB_PORT: ${PLAN_SERVICE_DB_PORT}
      PLAN_SERVICE_DB_NAME: ${PLAN_SERVICE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - backend

volumes:
  user-db-data:
  team-db-data:
  plan-db-data:

networks:
  backend:
